target("TestWeaselStats")
  set_kind("binary")
  add_files("./*.cpp")
  add_files("$(projectdir)/WeaselStats/TextMetrics.cpp")
  add_files("$(projectdir)/WeaselStats/WinSqlite.cpp")
  add_files("$(projectdir)/WeaselStats/InstallationIdentity.cpp")
  add_files("$(projectdir)/WeaselStats/StatsDatabase.cpp")
  add_files("$(projectdir)/WeaselStats/StatsReport.cpp")
  add_files("$(projectdir)/WeaselServer/InputStatisticsClient.cpp")
  add_rules("subcmd")
  add_links("kernel32")
  before_build(function(target)
    local target_dir = path.join(target:targetdir(), target:name())
    if not os.exists(target_dir) then
      os.mkdir(target_dir)
    end
    target:set("targetdir", target_dir)
  end)
